openapi: "3.0.0"
info:
  version: 1.0.0
  title: API description
servers:
  - url: http://localhost:8080
paths:
  /api/invoice/{documentName}:
    get:
      description: Download generated invoice document by document name
      operationId: getGeneratedInvoice
      tags:
        - invoice
      parameters:
        - name: documentName
          in: path
          required: true
          description: The generated document name as a path variable
          schema:
            type: string
      responses:
        '200':
          description: An expected response
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        '404':
          description: Document not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/invoice:
    post:
      description: Generate invoice document
      operationId: generateInvoice
      tags:
        - invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Record"
      responses:
        '200':
          description: URI to download generated file
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
  /api/record:
    get:
      description: Get list of invoice records
      operationId: getAllRecords
      tags:
        - record
      responses:
        '200':
          description: An expected response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Record"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  schemas:
    Record:
      type: object
      required:
        - name
        - amount
      properties:
        name:
          type: string
        amount:
          type: integer
          format: int32
          minimum: 0
    Response:
      type: object
      required:
        - attr
      properties:
        attr:
          type: string
    ApiError:
      type: object
      required:
        - httpCode
        - errorMessage
      properties:
        httpCode:
          type: integer
          format: int32
        errorMessage:
          type: string
