openapi: "3.0.0"
info:
  version: 1.0.0
  title: API description
servers:
  - url: http://localhost:8080
paths:
  /api/hello/{name}:
    get:
      description: Sample endpoint
      operationId: sayHello
      tags:
        - hello
      parameters:
        - name: name
          in: path
          required: true
          description: The name
          schema:
            type: string
      responses:
        '200':
          description: An expected response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Response"
        default:
          description: An unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiError"
components:
  schemas:
    Record:
      type: object
      required:
        - name
        - amount
      properties:
        name:
          type: string
        amount:
          type: integer
          format: int32
          minimum: 0
    Response:
      type: object
      required:
        - attr
      properties:
        attr:
          type: string
    ApiError:
      type: object
      required:
        - httpCode
        - errorMessage
      properties:
        httpCode:
          type: integer
          format: int32
        errorMessage:
          type: string
